language: node_js
node_js:
- '4'
env:
  global:
  - CXX=g++-4.8
  - GH_REF=github.com/open-contracting-partnership/ocp-data.git
  - DEPLOY_BRANCH=master
  - secure: nispVZK1ZlKsjUa8QzrWZuakW3eYvFuv8aJdvsuONOjnQzS6ahBQ5kTD+CLy3PnoQz1MU6dF69tiQp4VN0klXCTODSeCOaQ4u8QuRxKPJpVCl3BRqMGAw3F8I8m0TcuFZok5i1VZGrBJfUH0HlvHbvLLUvlvAVRrfQ17CCr8js9lqxiEms2QtHJ5PPm6O52JIhzgJlRKkXUB7eOsY+T0GveUBr/jeH4EWXIlXGaZ4pMKFSIF3XrWOp4V61/paWT03kqf0LLPmgKrbv609GDbFGBlsJ1peQvzxWf8nK/R+Zzs2D07a9UsGP1uvEZzat0i/Cgm7s/v4xQT1ZI6KGHsWjN96XloWYAI5D7nH8lziA3RU7pxULnSwQSszWpRJVaC8+NeLjHPQAbufiwDKEIXCVVDDduN2f9+rETwtbSwORiF9i/I6wMG4Xyj6KXyag09OiGBelCggWRze8ks3EEIhIRZ0QuIuJog8HX21vKGSFMCToJXv3YQLQjN7oMD3kGu1S+kpd9IBYihousPd2IxAJwofzq/eG9KeWsPk2YwgPlKpqK+etXOs1cugNX5YuR71mzu7QNZxyFc3KDIaIWj8V0xj8fqoahWn5b1G0FzmfAVUEi2s+RKXIz6ElhDbUyK2sVN1BThYp5RifuXrbx0InyzNhPEJgdwmPACyaKjZRM=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  apt: true
  directories:
  - node_modules
before_install:
- chmod +x ./.build_scripts/deploy.sh
- chmod +x ./.build_scripts/lint.sh
before_script:
- "./.build_scripts/lint.sh"
- npm test
script:
- npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: ".build_scripts/deploy.sh"
  on:
    branch: "${DEPLOY_BRANCH}"
